---
title: "p8105_hw4_wp2241"
author: "Weixin Peng"
date: "October 25, 2017"
output: html_document
---

### Preparation
```{r}
library(tidyverse)
library(janitor)
library(dplyr)
library(ggridges)
```

### Load and clean data
```{r}
pols_month = read_csv("./538_data/pols-month.csv")
gdp = read_csv("./538_data/GDP.csv") %>%
  janitor::clean_names() %>% 
  mutate(value = as.numeric(value))

pols_month = pols_month %>%
  mutate(president = prez_dem) %>%
  mutate(president = recode(president, '0' = "gop", '1' = "dem")) %>%
  select(-prez_gop, -prez_dem) %>%
  rename(date = mon) %>%
  mutate(
  date = lubridate::floor_date(date,"month"))

data = merge(gdp, pols_month, by = "date") %>%
  filter(value != ".")
#data cleared


```

### Make a GDP plot
```{r}
ggplot(data, aes(x = date, y = value)) + 
  geom_point(aes(color = president), alpha = .5) + 
  geom_line() +
  labs(
    title = "GDP over time",
    x = "date",
    y = "DGP value",
    caption = "Data from the 538 dataset"
  ) + 
  theme(legend.position = "bottom")

```

* Comment: From the plot we creat above, we find that the GDP value varys a lot from year to year, especially in the 1930s. For most of the years, the GDP value is above 0, but there exist some year that the GDP is negative value, such as the 1933 and 2007.